language: python
python: 3.6
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox &
  - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip && sudo unzip chromedriver_linux64.zip -d /usr/local/bin/ && rm -f chromedriver_linux64.zip
  - pip install selenium
install: true
script: python tests.py
